FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .

# Railway injects build-time variables; Dockerfile needs ARG declarations.
ARG VITE_API_URL
ARG VITE_TON_CONNECT_MANIFEST_URL
ARG VITE_TON_NETWORK
ARG VITE_ENABLE_ANALYTICS
ARG VITE_FEATURE_CHANNEL_ANALYTICS
ARG VITE_FEATURE_TON_ESCROW
ARG VITE_DEAL_CHAT_DELETE_TOPICS_ON_CLOSE
ARG VITE_SUPPORTED_CURRENCIES
ARG VITE_DEFAULT_CURRENCY
ARG VITE_FORCE_THEME

ENV VITE_API_URL=$VITE_API_URL \
    VITE_TON_CONNECT_MANIFEST_URL=$VITE_TON_CONNECT_MANIFEST_URL \
    VITE_TON_NETWORK=$VITE_TON_NETWORK \
    VITE_ENABLE_ANALYTICS=$VITE_ENABLE_ANALYTICS \
    VITE_FEATURE_CHANNEL_ANALYTICS=$VITE_FEATURE_CHANNEL_ANALYTICS \
    VITE_FEATURE_TON_ESCROW=$VITE_FEATURE_TON_ESCROW \
    VITE_DEAL_CHAT_DELETE_TOPICS_ON_CLOSE=$VITE_DEAL_CHAT_DELETE_TOPICS_ON_CLOSE \
    VITE_SUPPORTED_CURRENCIES=$VITE_SUPPORTED_CURRENCIES \
    VITE_DEFAULT_CURRENCY=$VITE_DEFAULT_CURRENCY \
    VITE_FORCE_THEME=$VITE_FORCE_THEME

RUN npm run build

FROM caddy:2-alpine AS runner
WORKDIR /srv

COPY --from=builder /app/dist ./
COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 8080
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
